version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gymlog_db
    volumes:
      - ./mysql/create-auth-tables.sql:/docker-entrypoint-initdb.d/1-auth.sql
      - ./mysql/create-tables.sql:/docker-entrypoint-initdb.d/2-tables.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gymlog:
    build: .
    container_name: gymlog_jvm
    image: gymlog:latest
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      - ENV_CONFIG=dev
      - ENC_ALGORITHM=PBEWithMD5AndTripleDES
      - ENC_PASSWORD=foobar